[fisher]

indir = /work/anemmani/noise-folder/gaussian-O4  # input data directory (string)
outdir = test            # output directory (string)
band = 17             # band number (int)
seg = 1               # segment number (int)
nod = 6               # length of input time series [days] (int)
dt = 0.5              # input time series sampling interval [seconds] (double)
overlap = 0.0625      # bands overlap, band frequency fpo=10+(1-overlap)*B/(2*dt) (double)
addsig = pulsar-10             # name of the file with signals to be injected

# optional
usedet =              # use specified detectors, if empty use all detectors found in indir
label =               # label for output files, if empty use default label
mods =                # modifiers, not supported values: "systematics"
