[coincidences]
refr = 50                 ; reference frame
cthr = 16.5               ; Fstatistic threshold for coincidences
#hemi = 0                  ; hemisphere to consider (1||2||0 for both)
scalem = 2                ; cell scale factor for m
scalen = 2                ; cell scale factor for n
scales = 4                ; cell scale factor for s
scalef = 128              ; cell scale factor for fbin
shift =               ; cell shifts, if empty loop over all 16 permutations
mincoin = 4               ; minimum number of coincidences to register
out_dir = .               ; output directory, cwd by default
trig_dset = triggers      ; read triggers from this dataset (triggers||injections)
coinc_dset = coinc_       ; write coincidences to dataset: coinc_{shift}
write_ctrigs = 1          ; write shifted triggers to HDF file
trig_file_list = \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_006_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_007_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_008_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_009_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_010_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_012_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_014_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_015_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_016_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_017_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_018_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_019_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_020_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_021_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_022_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_023_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_025_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_028_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_029_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_037_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_055_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_056_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_058_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_060_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_062_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_063_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_065_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_066_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_078_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_081_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_082_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_093_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_094_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_096_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_099_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_103_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_104_0017_1.h5 \
/work/chuck/virgo/O4/O4-allsky-results/0017/triggers_105_0017_1.h5
